default:
  controller: "Front"
  action: "home"

contact:
  controller: "Front"
  action: "contact"

connexion:
  controller: "Security"
  action: "login"

s-inscrire:
  controller: "Security"
  action: "register"

login:
  controller: "Security"
  action: "login"

deconnexion:
  controller: "Security"
  action: "logout"

admin:
  controller: Backoffice
  action: index

admin/users:
  controller: Backoffice
  action: manageUsers

admin/reservations:
  controller: Backoffice
  action: manageReservations

reservation:
  controller : "Front"
  action : "reservation"

admin/reservation/edit/{id}:
  controller: Backoffice
  action: editReservation

admin/reservation/update/{id}:
  controller: Backoffice
  action: updateReservation

admin/reservation/delete/{id}:
  controller: Backoffice
  action: deleteReservation