default:
  controller: "Front"
  action: "home"

contact:
  controller: "Front"
  action: "contact"

connexion:
  controller: "Security"
  action: "login"

s-inscrire:
  controller: "Security"
  action: "register"

s-inscrire2:
  controller: "Security"
  action: "register2"

login:
  controller: "Security"
  action: "login"

deconnexion:
  controller: "Security"
  action: "logout"

admin:
  controller: Backoffice
  action: index
  auth: true
  role: [admin, editor]

admin/users:
  controller: Backoffice
  action: manageUsers
  auth: true
  role: [admin, editor]

admin/edituser:
  controller: Backoffice
  action: editUser
  auth: true
  role: [admin, editor]

admin/updateuser:
  controller: Backoffice
  action: updateUser
  auth: true
  role: [admin, editor]

admin/deleteuser:
  controller: Backoffice
  action: deleteuser
  auth: true
  role: [admin, editor]
