default:
  controller: "Front"
  action: "home"

contact:
  controller: "Front"
  action: "contact"

connexion:
  controller: "Security"
  action: "login"

s-inscrire:
  controller: "Security"
  action: "register"

login:
  controller: "Security"
  action: "login"

deconnexion:
  controller: "Security"
  action: "logout"

admin:
  controller: Backoffice
  action: index

admin/users:
  controller: Backoffice
  action: manageUsers

admin/recipes:
  controller: Backoffice  
  action: manageRecipes

admin/deleterecipe:
  controller: Backoffice  
  action: deleteRecipe

recipes:
  controller: Front
  action: displayRecipes