default:
  controller: "Front"
  action: "home"

contact:
  controller: "Front"
  action: "contact"

connexion:
  controller: "Security"
  action: "login"

s-inscrire:
  controller: "Security"
  action: "register"

email-confirmation:
  controller: "Security"
  action: "confirmEmail"

login:
  controller: "Security"
  action: "login"

deconnexion:
  controller: "Security"
  action: "logout"

admin:
  controller: Backoffice
  action: index
  role: [admin, editor]

admin/users:
  controller: Backoffice
  action: manageUsers
  role: [admin, editor]

admin/edituser:
  controller: Backoffice
  action: editUser
  role: [admin, editor]

admin/updateuser:
  controller: Backoffice
  action: updateUser
  role: [admin, editor]

admin/deleteuser:
  controller: Backoffice
  action: deleteuser
  role: [admin, editor]

admin/pages:
  controller: Backoffice
  action: managePages

admin/editpage:
  controller: Backoffice
  action: editPage

admin/updatepage:
  controller: Backoffice
  action: updatePage

admin/deletepage:
  controller: Backoffice
  action: deletePage
  
admin/recipes:
  controller: Backoffice
  action: manageRecipes

admin/editrecipe:
  controller: Backoffice
  action: editRecipe

admin/updaterecipe:
  controller: Backoffice
  action: updateRecipe

admin/deleterecipe:
  controller: Backoffice
  action: deleteRecipe

admin/categories:
  controller: Backoffice
  action: manageCategories

admin/editcategorie:
  controller: Backoffice
  action: editCategorie

admin/updatecategorie:
  controller: Backoffice
  action: updateCategorie

admin/deletecategorie:
  controller: Backoffice
  action: deleteCategorie